<?php 
/**
 * Themify Icon from https://themify.me/themify-icons
 *
 * @param $icons - taken from filter - vc_map param field settings['source'] provided icons (default empty array).
 * If array categorized it will auto-enable category dropdown
 *
 * @since 1.0
 * @return array - of icons for iconpicker, can be categorized, or not.
 */
add_filter( 'vc_iconpicker-type-themify', 'vc_iconpicker_type_themify' );

function vc_iconpicker_type_themify( $icons ) {

	$themify_icons = array(
		array( 'ti-arrow-up' => esc_html__( 'arrow-up', 'foldery' ) ),
		array( 'ti-arrow-right' => esc_html__( 'arrow-right', 'foldery' ) ),
		array( 'ti-arrow-left' => esc_html__( 'arrow-left', 'foldery' ) ),
		array( 'ti-arrow-down' => esc_html__( 'arrow-down', 'foldery' ) ),
		array( 'ti-arrows-vertical' => esc_html__( 'arrows-vertical', 'foldery' ) ),
		array( 'ti-arrows-horizontal' => esc_html__( 'arrows-horizontal', 'foldery' ) ),
		array( 'ti-angle-up' => esc_html__( 'angle-up', 'foldery' ) ),
		array( 'ti-angle-right' => esc_html__( 'angle-right', 'foldery' ) ),
		array( 'ti-angle-left' => esc_html__( 'angle-left', 'foldery' ) ),
		array( 'ti-angle-down' => esc_html__( 'angle-down', 'foldery' ) ),	
		array( 'ti-angle-double-up' => esc_html__( 'angle-double-up', 'foldery' ) ),
		array( 'ti-angle-double-right' => esc_html__( 'angle-double-right', 'foldery' ) ),
		array( 'ti-angle-double-left' => esc_html__( 'angle-double-left', 'foldery' ) ),
		array( 'ti-angle-double-down' => esc_html__( 'angle-double-down', 'foldery' ) ),
		array( 'ti-move' => esc_html__( 'move', 'foldery' ) ),
		array( 'ti-fullscreen' => esc_html__( 'fullscreen', 'foldery' ) ),
		array( 'ti-arrow-top-right' => esc_html__( 'arrow-top-right', 'foldery' ) ),
		array( 'ti-arrow-top-left' => esc_html__( 'arrow-top-left', 'foldery' ) ),
		array( 'ti-arrow-circle-up' => esc_html__( 'arrow-circle-up', 'foldery' ) ),
		array( 'ti-arrow-circle-right' => esc_html__( 'arrow-circle-right', 'foldery' ) ),
		array( 'ti-arrow-circle-left' => esc_html__( 'arrow-circle-left', 'foldery' ) ),
		array( 'ti-arrow-circle-down' => esc_html__( 'arrow-circle-down', 'foldery' ) ),
		array( 'ti-arrows-corner' => esc_html__( 'arrows-corner', 'foldery' ) ),
		array( 'ti-split-v' => esc_html__( 'split-v', 'foldery' ) ),

		array( 'ti-split-v-alt' => esc_html__( 'split-v-alt', 'foldery' ) ),
		array( 'ti-split-h' => esc_html__( 'split-h', 'foldery' ) ),
		array( 'ti-hand-point-up' => esc_html__( 'hand-point-up', 'foldery' ) ),
		array( 'ti-hand-point-right' => esc_html__( 'hand-point-right', 'foldery' ) ),
		array( 'ti-hand-point-left' => esc_html__( 'hand-point-left', 'foldery' ) ),
		array( 'ti-hand-point-down' => esc_html__( 'hand-point-down', 'foldery' ) ),
		array( 'ti-back-right' => esc_html__( 'back-right', 'foldery' ) ),
		array( 'ti-back-left' => esc_html__( 'back-left', 'foldery' ) ),
		array( 'ti-exchange-vertical' => esc_html__( 'exchange-vertical', 'foldery' ) ),
		array( 'ti-wand' => esc_html__( 'wand', 'foldery' ) ),
		array( 'ti-save' => esc_html__( 'save', 'foldery' ) ),
		array( 'ti-save-alt' => esc_html__( 'save-alt', 'foldery' ) ),

		array( 'ti-direction' => esc_html__( 'direction', 'foldery' ) ),
		array( 'ti-direction-alt' => esc_html__( 'direction-alt', 'foldery' ) ),
		array( 'ti-user' => esc_html__( 'user', 'foldery' ) ),
		array( 'ti-link' => esc_html__( 'link', 'foldery' ) ),
		array( 'ti-unlink' => esc_html__( 'unlink', 'foldery' ) ),
		array( 'ti-trash' => esc_html__( 'trash', 'foldery' ) ),
		array( 'ti-target' => esc_html__( 'target', 'foldery' ) ),
		array( 'ti-tag' => esc_html__( 'tag', 'foldery' ) ),
		array( 'ti-desktop' => esc_html__( 'desktop', 'foldery' ) ),
		array( 'ti-tablet' => esc_html__( 'tablet', 'foldery' ) ),
		array( 'ti-mobile' => esc_html__( 'mobile', 'foldery' ) ),
		array( 'ti-email' => esc_html__( 'email', 'foldery' ) ),
		array( 'ti-star' => esc_html__( 'star', 'foldery' ) ),
		array( 'ti-spray' => esc_html__( 'spray', 'foldery' ) ),
		array( 'ti-signal' => esc_html__( 'signal', 'foldery' ) ),
		array( 'ti-shopping-cart' => esc_html__( 'shopping-cart', 'foldery' ) ),
		array( 'ti-shopping-cart-full' => esc_html__( 'shopping-cart-full', 'foldery' ) ),
		array( 'ti-settings' => esc_html__( 'settings', 'foldery' ) ),
		array( 'ti-search' => esc_html__( 'search', 'foldery' ) ),
		array( 'ti-zoom-in' => esc_html__( 'zoom-in', 'foldery' ) ),
		array( 'ti-zoom-out' => esc_html__( 'zoom-out', 'foldery' ) ),
		array( 'ti-cut' => esc_html__( 'cut', 'foldery' ) ),
		array( 'ti-ruler' => esc_html__( 'ruler', 'foldery' ) ),
		array( 'ti-ruler-alt-2' => esc_html__( 'ruler-alt-2', 'foldery' ) ),			
		array( 'ti-ruler-pencil' => esc_html__( 'ruler-pencil', 'foldery' ) ),
		array( 'ti-ruler-alt' => esc_html__( 'ruler-alt', 'foldery' ) ),
		array( 'ti-bookmark' => esc_html__( 'bookmark', 'foldery' ) ),
		array( 'ti-bookmark-alt' => esc_html__( 'bookmark-alt', 'foldery' ) ),
		array( 'ti-reload' => esc_html__( 'reload', 'foldery' ) ),
		array( 'ti-plus' => esc_html__( 'plus', 'foldery' ) ),
		array( 'ti-minus' => esc_html__( 'minus', 'foldery' ) ),
		array( 'ti-close' => esc_html__( 'close', 'foldery' ) ),			
		array( 'ti-pin' => esc_html__( 'pin', 'foldery' ) ),
		array( 'ti-pencil' => esc_html__( 'pencil', 'foldery' ) ),
				
		array( 'ti-pencil-alt' => esc_html__( 'pencil-alt', 'foldery' ) ),
		array( 'ti-paint-roller' => esc_html__( 'paint-roller', 'foldery' ) ),
		array( 'ti-paint-bucket' => esc_html__( 'paint-bucket', 'foldery' ) ),
		array( 'ti-na' => esc_html__( 'na', 'foldery' ) ),
		array( 'ti-medall' => esc_html__( 'medall', 'foldery' ) ),
		array( 'ti-medall-alt' => esc_html__( 'medall-alt', 'foldery' ) ),
		array( 'ti-marker' => esc_html__( 'marker', 'foldery' ) ),
		array( 'ti-marker-alt' => esc_html__( 'marker-alt', 'foldery' ) ),

		array( 'ti-lock' => esc_html__( 'lock', 'foldery' ) ),
		array( 'ti-unlock' => esc_html__( 'unlock', 'foldery' ) ),
		array( 'ti-location-arrow' => esc_html__( 'location-arrow', 'foldery' ) ),
		array( 'ti-layout' => esc_html__( 'layout', 'foldery' ) ),
		array( 'ti-layers' => esc_html__( 'layers', 'foldery' ) ),
		array( 'ti-layers-alt' => esc_html__( 'layers-alt', 'foldery' ) ),
		array( 'ti-key' => esc_html__( 'key', 'foldery' ) ),
		array( 'ti-image' => esc_html__( 'image', 'foldery' ) ),
		array( 'ti-heart' => esc_html__( 'heart', 'foldery' ) ),
		array( 'ti-heart-broken' => esc_html__( 'heart-broken', 'foldery' ) ),
		array( 'ti-hand-stop' => esc_html__( 'hand-stop', 'foldery' ) ),
		array( 'ti-hand-open' => esc_html__( 'hand-open', 'foldery' ) ),
		array( 'ti-hand-drag' => esc_html__( 'hand-drag', 'foldery' ) ),
		array( 'ti-flag' => esc_html__( 'flag', 'foldery' ) ),
		array( 'ti-flag-alt' => esc_html__( 'flag-alt', 'foldery' ) ),
		array( 'ti-flag-alt-2' => esc_html__( 'flag-alt-2', 'foldery' ) ),
		array( 'ti-eye' => esc_html__( 'eye', 'foldery' ) ),
		array( 'ti-import' => esc_html__( 'import', 'foldery' ) ),			
		array( 'ti-export' => esc_html__( 'export', 'foldery' ) ),
		array( 'ti-cup' => esc_html__( 'cup', 'foldery' ) ),
		array( 'ti-crown' => esc_html__( 'crown', 'foldery' ) ),
		array( 'ti-comments' => esc_html__( 'comments', 'foldery' ) ),
		array( 'ti-comment' => esc_html__( 'comment', 'foldery' ) ),
		array( 'ti-comment-alt' => esc_html__( 'comment-alt', 'foldery' ) ),
		array( 'ti-thought' => esc_html__( 'thought', 'foldery' ) ),			
		array( 'ti-clip' => esc_html__( 'clip', 'foldery' ) ),

		array( 'ti-check' => esc_html__( 'check', 'foldery' ) ),
		array( 'ti-check-box' => esc_html__( 'check-box', 'foldery' ) ),
		array( 'ti-camera' => esc_html__( 'camera', 'foldery' ) ),
		array( 'ti-announcement' => esc_html__( 'announcement', 'foldery' ) ),
		array( 'ti-brush' => esc_html__( 'brush', 'foldery' ) ),
		array( 'ti-brush-alt' => esc_html__( 'brush-alt', 'foldery' ) ),
		array( 'ti-palette' => esc_html__( 'palette', 'foldery' ) ),			
		array( 'ti-briefcase' => esc_html__( 'briefcase', 'foldery' ) ),
		array( 'ti-bolt' => esc_html__( 'bolt', 'foldery' ) ),
		array( 'ti-bolt-alt' => esc_html__( 'bolt-alt', 'foldery' ) ),
		array( 'ti-blackboard' => esc_html__( 'blackboard', 'foldery' ) ),
		array( 'ti-bag' => esc_html__( 'bag', 'foldery' ) ),
		array( 'ti-world' => esc_html__( 'world', 'foldery' ) ),
		array( 'ti-wheelchair' => esc_html__( 'wheelchair', 'foldery' ) ),
		array( 'ti-car' => esc_html__( 'car', 'foldery' ) ),
		array( 'ti-truck' => esc_html__( 'truck', 'foldery' ) ),
		array( 'ti-timer' => esc_html__( 'timer', 'foldery' ) ),
		array( 'ti-ticket' => esc_html__( 'ticket', 'foldery' ) ),
		array( 'ti-thumb-up' => esc_html__( 'thumb-up', 'foldery' ) ),
		array( 'ti-thumb-down' => esc_html__( 'thumb-down', 'foldery' ) ),

		array( 'ti-stats-up' => esc_html__( 'stats-up', 'foldery' ) ),
		array( 'ti-stats-down' => esc_html__( 'stats-down', 'foldery' ) ),
		array( 'ti-shine' => esc_html__( 'shine', 'foldery' ) ),
		array( 'ti-shift-right' => esc_html__( 'shift-right', 'foldery' ) ),
		array( 'ti-shift-left' => esc_html__( 'shift-left', 'foldery' ) ),

		array( 'ti-shift-right-alt' => esc_html__( 'shift-right-alt', 'foldery' ) ),
		array( 'ti-shift-left-alt' => esc_html__( 'shift-left-alt', 'foldery' ) ),
		array( 'ti-shield' => esc_html__( 'shield', 'foldery' ) ),
		array( 'ti-notepad' => esc_html__( 'notepad', 'foldery' ) ),
		array( 'ti-server' => esc_html__( 'server', 'foldery' ) ),

		array( 'ti-pulse' => esc_html__( 'pulse', 'foldery' ) ),
		array( 'ti-printer' => esc_html__( 'printer', 'foldery' ) ),
		array( 'ti-power-off' => esc_html__( 'power-off', 'foldery' ) ),
		array( 'ti-plug' => esc_html__( 'plug', 'foldery' ) ),
		array( 'ti-pie-chart' => esc_html__( 'pie-chart', 'foldery' ) ),

		array( 'ti-panel' => esc_html__( 'panel', 'foldery' ) ),
		array( 'ti-package' => esc_html__( 'package', 'foldery' ) ),
		array( 'ti-music' => esc_html__( 'music', 'foldery' ) ),
		array( 'ti-music-alt' => esc_html__( 'music-alt', 'foldery' ) ),
		array( 'ti-mouse' => esc_html__( 'mouse', 'foldery' ) ),
		array( 'ti-mouse-alt' => esc_html__( 'mouse-alt', 'foldery' ) ),
		array( 'ti-money' => esc_html__( 'money', 'foldery' ) ),
		array( 'ti-microphone' => esc_html__( 'microphone', 'foldery' ) ),
		array( 'ti-menu' => esc_html__( 'menu', 'foldery' ) ),
		array( 'ti-menu-alt' => esc_html__( 'menu-alt', 'foldery' ) ),
		array( 'ti-map' => esc_html__( 'map', 'foldery' ) ),
		array( 'ti-map-alt' => esc_html__( 'map-alt', 'foldery' ) ),

		array( 'ti-location-pin' => esc_html__( 'location-pin', 'foldery' ) ),

		array( 'ti-light-bulb' => esc_html__( 'light-bulb', 'foldery' ) ),
		array( 'ti-info' => esc_html__( 'info', 'foldery' ) ),
		array( 'ti-infinite' => esc_html__( 'infinite', 'foldery' ) ),
		array( 'ti-id-badge' => esc_html__( 'id-badge', 'foldery' ) ),
		array( 'ti-hummer' => esc_html__( 'hummer', 'foldery' ) ),
		array( 'ti-home' => esc_html__( 'home', 'foldery' ) ),
		array( 'ti-help' => esc_html__( 'help', 'foldery' ) ),
		array( 'ti-headphone' => esc_html__( 'headphone', 'foldery' ) ),
		array( 'ti-harddrives' => esc_html__( 'harddrives', 'foldery' ) ),
		array( 'ti-harddrive' => esc_html__( 'harddrive', 'foldery' ) ),
		array( 'ti-gift' => esc_html__( 'gift', 'foldery' ) ),
		array( 'ti-game' => esc_html__( 'game', 'foldery' ) ),
		array( 'ti-filter' => esc_html__( 'filter', 'foldery' ) ),
		array( 'ti-files' => esc_html__( 'files', 'foldery' ) ),
		array( 'ti-file' => esc_html__( 'file', 'foldery' ) ),
		array( 'ti-zip' => esc_html__( 'zip', 'foldery' ) ),
		array( 'ti-folder' => esc_html__( 'folder', 'foldery' ) ),			
		array( 'ti-envelope' => esc_html__( 'envelope', 'foldery' ) ),


		array( 'ti-dashboard' => esc_html__( 'dashboard', 'foldery' ) ),
		array( 'ti-cloud' => esc_html__( 'cloud', 'foldery' ) ),
		array( 'ti-cloud-up' => esc_html__( 'cloud-up', 'foldery' ) ),
		array( 'ti-cloud-down' => esc_html__( 'cloud-down', 'foldery' ) ),
		array( 'ti-clipboard' => esc_html__( 'clipboard', 'foldery' ) ),
		array( 'ti-calendar' => esc_html__( 'calendar', 'foldery' ) ),
		array( 'ti-book' => esc_html__( 'book', 'foldery' ) ),
		array( 'ti-bell' => esc_html__( 'bell', 'foldery' ) ),
		array( 'ti-basketball' => esc_html__( 'basketball', 'foldery' ) ),
		array( 'ti-bar-chart' => esc_html__( 'bar-chart', 'foldery' ) ),
		array( 'ti-bar-chart-alt' => esc_html__( 'bar-chart-alt', 'foldery' ) ),


		array( 'ti-archive' => esc_html__( 'archive', 'foldery' ) ),
		array( 'ti-anchor' => esc_html__( 'anchor', 'foldery' ) ),

		array( 'ti-alert' => esc_html__( 'alert', 'foldery' ) ),
		array( 'ti-alarm-clock' => esc_html__( 'alarm-clock', 'foldery' ) ),
		array( 'ti-agenda' => esc_html__( 'agenda', 'foldery' ) ),
		array( 'ti-write' => esc_html__( 'write', 'foldery' ) ),

		array( 'ti-wallet' => esc_html__( 'wallet', 'foldery' ) ),
		array( 'ti-video-clapper' => esc_html__( 'video-clapper', 'foldery' ) ),
		array( 'ti-video-camera' => esc_html__( 'video-camera', 'foldery' ) ),
		array( 'ti-vector' => esc_html__( 'vector', 'foldery' ) ),

		array( 'ti-support' => esc_html__( 'support', 'foldery' ) ),
		array( 'ti-stamp' => esc_html__( 'stamp', 'foldery' ) ),
		array( 'ti-slice' => esc_html__( 'slice', 'foldery' ) ),
		array( 'ti-shortcode' => esc_html__( 'shortcode', 'foldery' ) ),
		array( 'ti-receipt' => esc_html__( 'receipt', 'foldery' ) ),
		array( 'ti-pin2' => esc_html__( 'pin2', 'foldery' ) ),
		array( 'ti-pin-alt' => esc_html__( 'pin-alt', 'foldery' ) ),
		array( 'ti-pencil-alt2' => esc_html__( 'pencil-alt2', 'foldery' ) ),
		array( 'ti-eraser' => esc_html__( 'eraser', 'foldery' ) ),			
		array( 'ti-more' => esc_html__( 'more', 'foldery' ) ),
		array( 'ti-more-alt' => esc_html__( 'more-alt', 'foldery' ) ),
		array( 'ti-microphone-alt' => esc_html__( 'microphone-alt', 'foldery' ) ),
		array( 'ti-magnet' => esc_html__( 'magnet', 'foldery' ) ),
		array( 'ti-line-double' => esc_html__( 'line-double', 'foldery' ) ),
		array( 'ti-line-dotted' => esc_html__( 'line-dotted', 'foldery' ) ),
		array( 'ti-line-dashed' => esc_html__( 'line-dashed', 'foldery' ) ),

		array( 'ti-ink-pen' => esc_html__( 'ink-pen', 'foldery' ) ),
		array( 'ti-info-alt' => esc_html__( 'info-alt', 'foldery' ) ),
		array( 'ti-help-alt' => esc_html__( 'help-alt', 'foldery' ) ),
		array( 'ti-headphone-alt' => esc_html__( 'headphone-alt', 'foldery' ) ),

		array( 'ti-gallery' => esc_html__( 'gallery', 'foldery' ) ),
		array( 'ti-face-smile' => esc_html__( 'face-smile', 'foldery' ) ),
		array( 'ti-face-sad' => esc_html__( 'face-sad', 'foldery' ) ),
		array( 'ti-credit-card' => esc_html__( 'credit-card', 'foldery' ) ),
		array( 'ti-comments-smiley' => esc_html__( 'comments-smiley', 'foldery' ) ),
		array( 'ti-time' => esc_html__( 'time', 'foldery' ) ),
		array( 'ti-share' => esc_html__( 'share', 'foldery' ) ),
		array( 'ti-share-alt' => esc_html__( 'share-alt', 'foldery' ) ),
		array( 'ti-rocket' => esc_html__( 'rocket', 'foldery' ) ),

		array( 'ti-new-window' => esc_html__( 'new-window', 'foldery' ) ),

		array( 'ti-rss' => esc_html__( 'rss', 'foldery' ) ),

		array( 'ti-rss-alt' => esc_html__( 'rss-alt', 'foldery' ) ),
		array( 'ti-control-stop' => esc_html__( 'control-stop', 'foldery' ) ),
		array( 'ti-control-shuffle' => esc_html__( 'control-shuffle', 'foldery' ) ),
		array( 'ti-control-play' => esc_html__( 'control-play', 'foldery' ) ),
		array( 'ti-control-pause' => esc_html__( 'control-pause', 'foldery' ) ),
		array( 'ti-control-forward' => esc_html__( 'control-forward', 'foldery' ) ),
		array( 'ti-control-backward' => esc_html__( 'control-backward', 'foldery' ) ),	
		array( 'ti-volume' => esc_html__( 'volume', 'foldery' ) ),
		array( 'ti-control-skip-forward' => esc_html__( 'control-skip-forward', 'foldery' ) ),
		array( 'ti-control-skip-backward' => esc_html__( 'control-skip-backward', 'foldery' ) ),
		array( 'ti-control-record' => esc_html__( 'control-record', 'foldery' ) ),
		array( 'ti-control-eject' => esc_html__( 'control-eject', 'foldery' ) ),
		array( 'ti-paragraph' => esc_html__( 'paragraph', 'foldery' ) ),
		array( 'ti-uppercase' => esc_html__( 'uppercase', 'foldery' ) ),

		array( 'ti-underline' => esc_html__( 'underline', 'foldery' ) ),
		array( 'ti-text' => esc_html__( 'ti-text', 'foldery' ) ),
		array( 'ti-Italic' => esc_html__( 'Italic', 'foldery' ) ),
		array( 'ti-smallcap' => esc_html__( 'smallcap', 'foldery' ) ),
		array( 'ti-list' => esc_html__( 'list', 'foldery' ) ),
		array( 'ti-list-ol' => esc_html__( 'list-ol', 'foldery' ) ),
		array( 'ti-align-right' => esc_html__( 'align-right', 'foldery' ) ),
		array( 'ti-align-left' => esc_html__( 'align-left', 'foldery' ) ),
		array( 'ti-align-justify' => esc_html__( 'align-justify', 'foldery' ) ),
		array( 'ti-align-center' => esc_html__( 'align-center', 'foldery' ) ),
		array( 'ti-quote-right' => esc_html__( 'quote-right', 'foldery' ) ),
		array( 'ti-quote-left' => esc_html__( 'quote-left', 'foldery' ) ),
		array( 'ti-layout-width-full' => esc_html__( 'layout-width-full', 'foldery' ) ),
		array( 'ti-layout-width-default' => esc_html__( 'layout-width-default', 'foldery' ) ),
		array( 'ti-layout-width-default-alt' => esc_html__( 'layout-width-default-alt', 'foldery' ) ),
		array( 'ti-layout-tab' => esc_html__( 'layout-tab', 'foldery' ) ),
		array( 'ti-layout-tab-window' => esc_html__( 'layout-tab-window', 'foldery' ) ),
		array( 'ti-layout-tab-v' => esc_html__( 'layout-tab-v', 'foldery' ) ),
		array( 'ti-layout-tab-min' => esc_html__( 'layout-tab-min', 'foldery' ) ),
		array( 'ti-layout-slider' => esc_html__( 'layout-slider', 'foldery' ) ),
		array( 'ti-layout-slider-alt' => esc_html__( 'layout-slider-alt', 'foldery' ) ),
		array( 'ti-layout-sidebar-right' => esc_html__( 'layout-sidebar-right', 'foldery' ) ),
		array( 'ti-layout-sidebar-none' => esc_html__( 'layout-sidebar-none', 'foldery' ) ),
		array( 'ti-layout-sidebar-left' => esc_html__( 'layout-sidebar-left', 'foldery' ) ),
		array( 'ti-layout-placeholder' => esc_html__( 'layout-placeholder', 'foldery' ) ),
		array( 'ti-layout-menu' => esc_html__( 'layout-menu', 'foldery' ) ),
		array( 'ti-layout-menu-v' => esc_html__( 'layout-menu-v', 'foldery' ) ),
		array( 'ti-layout-menu-separated' => esc_html__( 'layout-menu-separated', 'foldery' ) ),
		array( 'ti-layout-menu-full' => esc_html__( 'layout-menu-full', 'foldery' ) ),
		array( 'ti-layout-media-right' => esc_html__( 'layout-media-right', 'foldery' ) ),
		array( 'ti-layout-media-right-alt' => esc_html__( 'layout-media-right-alt', 'foldery' ) ),
		array( 'ti-layout-media-overlay' => esc_html__( 'layout-media-overlay', 'foldery' ) ),
		array( 'ti-layout-media-overlay-alt' => esc_html__( 'layout-media-overlay-alt', 'foldery' ) ),
		array( 'ti-layout-media-overlay-alt-2' => esc_html__( 'layout-media-overlay-alt-2', 'foldery' ) ),
		array( 'ti-layout-media-left' => esc_html__( 'layout-media-left', 'foldery' ) ),
		array( 'ti-layout-media-left-alt' => esc_html__( 'layout-media-left-alt', 'foldery' ) ),
		array( 'ti-layout-media-center' => esc_html__( 'layout-media-center', 'foldery' ) ),
		array( 'ti-layout-media-center-alt' => esc_html__( 'layout-media-center-alt', 'foldery' ) ),
		array( 'ti-layout-list-thumb' => esc_html__( 'layout-list-thumb', 'foldery' ) ),
		array( 'ti-layout-list-thumb-alt' => esc_html__( 'layout-list-thumb-alt', 'foldery' ) ),
		array( 'ti-layout-list-post' => esc_html__( 'layout-list-post', 'foldery' ) ),
		array( 'ti-layout-list-large-image' => esc_html__( 'layout-list-large-image', 'foldery' ) ),
		array( 'ti-layout-line-solid' => esc_html__( 'layout-line-solid', 'foldery' ) ),
		array( 'ti-layout-grid4' => esc_html__( 'layout-grid4', 'foldery' ) ),
		array( 'ti-layout-grid3' => esc_html__( 'layout-grid3', 'foldery' ) ),
		array( 'ti-layout-grid2' => esc_html__( 'layout-grid2', 'foldery' ) ),
		array( 'ti-layout-grid2-thumb' => esc_html__( 'layout-grid2-thumb', 'foldery' ) ),
		array( 'ti-layout-cta-right' => esc_html__( 'layout-cta-right', 'foldery' ) ),
		array( 'ti-layout-cta-left' => esc_html__( 'layout-cta-left', 'foldery' ) ),
		array( 'ti-layout-cta-center' => esc_html__( 'layout-cta-center', 'foldery' ) ),
		array( 'ti-layout-cta-btn-right' => esc_html__( 'layout-cta-btn-right', 'foldery' ) ),
		array( 'ti-layout-cta-btn-left' => esc_html__( 'layout-cta-btn-left', 'foldery' ) ),
		array( 'ti-layout-column4' => esc_html__( 'layout-column4', 'foldery' ) ),
		array( 'ti-layout-column3' => esc_html__( 'layout-column3', 'foldery' ) ),
		array( 'ti-layout-column2' => esc_html__( 'layout-column2', 'foldery' ) ),
		array( 'ti-layout-accordion-separated' => esc_html__( 'layout-accordion-separated', 'foldery' ) ),
		array( 'ti-layout-accordion-merged' => esc_html__( 'layout-accordion-merged', 'foldery' ) ),
		array( 'ti-layout-accordion-list' => esc_html__( 'layout-accordion-list', 'foldery' ) ),
		array( 'ti-widgetized' => esc_html__( 'widgetized', 'foldery' ) ),
		array( 'ti-widget' => esc_html__( 'widget', 'foldery' ) ),
		array( 'ti-widget-alt' => esc_html__( 'widget-alt', 'foldery' ) ),
		array( 'ti-view-list' => esc_html__( 'view-list', 'foldery' ) ),
		array( 'ti-view-list-alt' => esc_html__( 'view-list-alt', 'foldery' ) ),
		array( 'ti-view-grid' => esc_html__( 'view-grid', 'foldery' ) ),
		array( 'ti-upload' => esc_html__( 'upload', 'foldery' ) ),
		array( 'ti-download' => esc_html__( 'download', 'foldery' ) ),	
		array( 'ti-loop' => esc_html__( 'loop', 'foldery' ) ),
		array( 'ti-layout-sidebar-2' => esc_html__( 'layout-sidebar-2', 'foldery' ) ),
		array( 'ti-layout-grid4-alt' => esc_html__( 'layout-grid4-alt', 'foldery' ) ),
		array( 'ti-layout-grid3-alt' => esc_html__( 'layout-grid3-alt', 'foldery' ) ),
		array( 'ti-layout-grid2-alt' => esc_html__( 'layout-grid2-alt', 'foldery' ) ),
		array( 'ti-layout-column4-alt' => esc_html__( 'layout-column4-alt', 'foldery' ) ),
		array( 'ti-layout-column3-alt' => esc_html__( 'layout-column3-alt', 'foldery' ) ),
		array( 'ti-layout-column2-alt' => esc_html__( 'layout-column2-alt', 'foldery' ) ),
		array( 'ti-flickr' => esc_html__( 'flickr', 'foldery' ) ),
		array( 'ti-flickr-alt' => esc_html__( 'flickr-alt', 'foldery' ) ),			
		array( 'ti-instagram' => esc_html__( 'instagram', 'foldery' ) ),
		array( 'ti-google' => esc_html__( 'google', 'foldery' ) ),
		array( 'ti-github' => esc_html__( 'github', 'foldery' ) ),

		array( 'ti-facebook' => esc_html__( 'facebook', 'foldery' ) ),
		array( 'ti-dropbox' => esc_html__( 'dropbox', 'foldery' ) ),
		array( 'ti-dropbox-alt' => esc_html__( 'dropbox-alt', 'foldery' ) ),
		array( 'ti-dribbble' => esc_html__( 'dribbble', 'foldery' ) ),
		array( 'ti-apple' => esc_html__( 'apple', 'foldery' ) ),
		array( 'ti-android' => esc_html__( 'android', 'foldery' ) ),
		array( 'ti-yahoo' => esc_html__( 'yahoo', 'foldery' ) ),
		array( 'ti-trello' => esc_html__( 'trello', 'foldery' ) ),
		array( 'ti-stack-overflow' => esc_html__( 'stack-overflow', 'foldery' ) ),
		array( 'ti-soundcloud' => esc_html__( 'soundcloud', 'foldery' ) ),
		array( 'ti-sharethis' => esc_html__( 'sharethis', 'foldery' ) ),
		array( 'ti-sharethis-alt' => esc_html__( 'sharethis-alt', 'foldery' ) ),
		array( 'ti-reddit' => esc_html__( 'reddit', 'foldery' ) ),

		array( 'ti-microsoft' => esc_html__( 'microsoft', 'foldery' ) ),
		array( 'ti-microsoft-alt' => esc_html__( 'microsoft-alt', 'foldery' ) ),
		array( 'ti-linux' => esc_html__( 'linux', 'foldery' ) ),
		array( 'ti-jsfiddle' => esc_html__( 'jsfiddle', 'foldery' ) ),
		array( 'ti-joomla' => esc_html__( 'joomla', 'foldery' ) ),
		array( 'ti-html5' => esc_html__( 'html5', 'foldery' ) ),
		array( 'ti-css3' => esc_html__( 'css3', 'foldery' ) ),	
		array( 'ti-drupal' => esc_html__( 'drupal', 'foldery' ) ),
		array( 'ti-wordpress' => esc_html__( 'wordpress', 'foldery' ) ),		
		array( 'ti-tumblr' => esc_html__( 'tumblr', 'foldery' ) ),
		array( 'ti-tumblr-alt' => esc_html__( 'tumblr-alt', 'foldery' ) ),
		array( 'ti-skype' => esc_html__( 'skype', 'foldery' ) ),
		array( 'ti-youtube' => esc_html__( 'youtube', 'foldery' ) ),
		array( 'ti-vimeo' => esc_html__( 'vimeo', 'foldery' ) ),
		array( 'ti-vimeo-alt' => esc_html__( 'vimeo-alt', 'foldery' ) ),			
		array( 'ti-twitter' => esc_html__( 'twitter', 'foldery' ) ),
		array( 'ti-twitter-alt' => esc_html__( 'twitter-alt', 'foldery' ) ),
		array( 'ti-linkedin' => esc_html__( 'linkedin', 'foldery' ) ),
		array( 'ti-pinterest' => esc_html__( 'pinterest', 'foldery' ) ),

		array( 'ti-pinterest-alt' => esc_html__( 'pinterest-alt', 'foldery' ) ),
		array( 'ti-themify-logo' => esc_html__( 'themify-logo', 'foldery' ) ),
		array( 'ti-themify-favicon' => esc_html__( 'themify-favicon', 'foldery' ) ),
		array( 'ti-themify-favicon-alt' => esc_html__( 'themify-favicon-alt', 'foldery' ) ),
	);
	return array_merge( $icons, $themify_icons );
}
 ?>